---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xe85i.
--- DateTime: 2023/6/1 17:07
---

local voucherID = ARGV[1]
local userID = ARGV[2]

local stockKey = 'seckill:stock:' .. voucherID

local orderKey = 'seckill:order:' .. voucherID

-- 判断库存
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

if (redis.call('sismember', orderKey, userID) == 1) then
    return 2
end

-- 扣除库存
redis.call('incrby', stockKey, -1)

-- 下单（保存用户）
redis.call('sadd', orderKey, userID)
return 0